/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms/$slug'
import { Route as PartnerRoomsRouteImport } from './routes/partner/rooms'
import { Route as PartnerProfileRouteImport } from './routes/partner/profile'
import { Route as PartnerLoginRouteImport } from './routes/partner/login'
import { Route as PartnerInventoryRouteImport } from './routes/partner/inventory'
import { Route as PartnerBookingsRouteImport } from './routes/partner/bookings'
import { Route as MyBookingsIdRouteImport } from './routes/my-bookings/$id'
import { Route as BookingSuccessRouteImport } from './routes/booking/success'
import { Route as BookingFailedRouteImport } from './routes/booking/failed'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const PartnerRoomsRoute = PartnerRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerInventoryRoute = PartnerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerBookingsRoute = PartnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PartnerRoute,
} as any)
const MyBookingsIdRoute = MyBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyBookingsRoute,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFailedRoute = BookingFailedRouteImport.update({
  id: '/booking/failed',
  path: '/booking/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRoute
  '/journal': typeof JournalRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRouteWithChildren
  '/offers': typeof OffersRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/rooms': typeof PartnerRoomsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/booking/': typeof BookingIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRoute
  '/journal': typeof JournalRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRouteWithChildren
  '/offers': typeof OffersRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/rooms': typeof PartnerRoomsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/booking': typeof BookingIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRoute
  '/journal': typeof JournalRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRouteWithChildren
  '/offers': typeof OffersRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/partner/bookings': typeof PartnerBookingsRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/rooms': typeof PartnerRoomsRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/booking/': typeof BookingIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/company'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/hotels'
    | '/journal'
    | '/legal'
    | '/login'
    | '/my-bookings'
    | '/offers'
    | '/partner'
    | '/payment'
    | '/privacy'
    | '/refund'
    | '/refund-policy'
    | '/rooms'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/rooms'
    | '/admin/settings'
    | '/booking/failed'
    | '/booking/success'
    | '/my-bookings/$id'
    | '/partner/bookings'
    | '/partner/inventory'
    | '/partner/login'
    | '/partner/profile'
    | '/partner/rooms'
    | '/rooms/$slug'
    | '/admin/'
    | '/booking/'
    | '/partner/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/company'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/hotels'
    | '/journal'
    | '/legal'
    | '/login'
    | '/my-bookings'
    | '/offers'
    | '/payment'
    | '/privacy'
    | '/refund'
    | '/refund-policy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/rooms'
    | '/admin/settings'
    | '/booking/failed'
    | '/booking/success'
    | '/my-bookings/$id'
    | '/partner/bookings'
    | '/partner/inventory'
    | '/partner/login'
    | '/partner/profile'
    | '/partner/rooms'
    | '/rooms/$slug'
    | '/admin'
    | '/booking'
    | '/partner'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/company'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/hotels'
    | '/journal'
    | '/legal'
    | '/login'
    | '/my-bookings'
    | '/offers'
    | '/partner'
    | '/payment'
    | '/privacy'
    | '/refund'
    | '/refund-policy'
    | '/rooms'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/rooms'
    | '/admin/settings'
    | '/booking/failed'
    | '/booking/success'
    | '/my-bookings/$id'
    | '/partner/bookings'
    | '/partner/inventory'
    | '/partner/login'
    | '/partner/profile'
    | '/partner/rooms'
    | '/rooms/$slug'
    | '/admin/'
    | '/booking/'
    | '/partner/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsRoute: typeof BlogsRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HotelsRoute: typeof HotelsRoute
  JournalRoute: typeof JournalRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRouteWithChildren
  OffersRoute: typeof OffersRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BookingFailedRoute: typeof BookingFailedRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  BookingIndexRoute: typeof BookingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/partner/rooms': {
      id: '/partner/rooms'
      path: '/rooms'
      fullPath: '/partner/rooms'
      preLoaderRoute: typeof PartnerRoomsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/inventory': {
      id: '/partner/inventory'
      path: '/inventory'
      fullPath: '/partner/inventory'
      preLoaderRoute: typeof PartnerInventoryRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/bookings': {
      id: '/partner/bookings'
      path: '/bookings'
      fullPath: '/partner/bookings'
      preLoaderRoute: typeof PartnerBookingsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/my-bookings/$id': {
      id: '/my-bookings/$id'
      path: '/$id'
      fullPath: '/my-bookings/$id'
      preLoaderRoute: typeof MyBookingsIdRouteImport
      parentRoute: typeof MyBookingsRoute
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/failed': {
      id: '/booking/failed'
      path: '/booking/failed'
      fullPath: '/booking/failed'
      preLoaderRoute: typeof BookingFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyBookingsRouteChildren {
  MyBookingsIdRoute: typeof MyBookingsIdRoute
}

const MyBookingsRouteChildren: MyBookingsRouteChildren = {
  MyBookingsIdRoute: MyBookingsIdRoute,
}

const MyBookingsRouteWithChildren = MyBookingsRoute._addFileChildren(
  MyBookingsRouteChildren,
)

interface PartnerRouteChildren {
  PartnerBookingsRoute: typeof PartnerBookingsRoute
  PartnerInventoryRoute: typeof PartnerInventoryRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PartnerRoomsRoute: typeof PartnerRoomsRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerBookingsRoute: PartnerBookingsRoute,
  PartnerInventoryRoute: PartnerInventoryRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PartnerRoomsRoute: PartnerRoomsRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsRoute: BlogsRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HotelsRoute: HotelsRoute,
  JournalRoute: JournalRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRouteWithChildren,
  OffersRoute: OffersRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BookingFailedRoute: BookingFailedRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  BookingIndexRoute: BookingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
