/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels/$hotelId'
import { Route as BookingSuccessRouteImport } from './routes/booking/success'
import { Route as BookingFailedRouteImport } from './routes/booking/failed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFailedRoute = BookingFailedRouteImport.update({
  id: '/booking/failed',
  path: '/booking/failed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/booking/': typeof BookingIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/booking': typeof BookingIndexRoute
  '/hotels': typeof HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/success': typeof BookingSuccessRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/booking/': typeof BookingIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking/failed'
    | '/booking/success'
    | '/hotels/$hotelId'
    | '/booking/'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking/failed'
    | '/booking/success'
    | '/hotels/$hotelId'
    | '/booking'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/booking/failed'
    | '/booking/success'
    | '/hotels/$hotelId'
    | '/booking/'
    | '/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingFailedRoute: typeof BookingFailedRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  BookingIndexRoute: typeof BookingIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/failed': {
      id: '/booking/failed'
      path: '/booking/failed'
      fullPath: '/booking/failed'
      preLoaderRoute: typeof BookingFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingFailedRoute: BookingFailedRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  BookingIndexRoute: BookingIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
